datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

start = r

# variables
pos.values = "A" | "N" | "V" | "Adv" | "Po" | "Pr" | "Pron" | "Phrase" 
    | "Rel" | "Det" | "Interj" | "Pcle" | "Num" | "CC" | "CS" 
type.values = "Rel" | "Pers" | "Indef" | "Refl" | "Dem" | "G3" | "G7" | "NomAg"
    | "Ord" | "Prop" | "Recipr" | "Coll" | "Interr" | "ACR" | "ABBR"
# year (two digits) followed by a number: 2601, 2602, ...
batch.id = xsd:string { pattern = "[0-9]{2}[0-9]{2,}" }

# root and header
r = element r {
    attribute id { "dict-sme" }?,
    attribute xml:lang { "sme" }?,
    lics?,
    e+
}

lics = element lics {
    attribute xml:lang { "en" },
    attribute xml:space { "default" | "preserve" }?,
    lic,
    ref*,
    sourcenote*
}

lic = element lic {  mixed { a* } }
ref = element ref { mixed { a* } }
sourcenote = element sourcenote { mixed { a* } }
a = element a { text }

# entry
# batch: the batch the entry is in, see batches.xml
e = element e {
    attribute status { "edit" | "publish" },
    attribute batch { batch.id }?,
    lg,
    dg*,
    ig*,
    cg?
}

# lemma group
lg =
  element lg {
    attribute pos { pos.values },
    attribute type { type.values }?,
    l+
  }

# lemma
l = element l {
    text
}

# definiton group
dg = element dg {
    attribute id { text },
    d+,
    syng*,
    antg*,
    xg*
}

# definition
d = element d { mixed { d_ref* } }

# refrence to other relevent definition
d_ref = element d_ref {
    attribute lemma { text },
    attribute pos { text },
    attribute type { text },
    attribute dg_id { text },
    text
}

# synonyms
syng = element syng { element syn { text }+ }

# antonyms
antg = element antg { element ant { text }+ }

# example group
xg = element xg {
    element x { text }+
}


# idiom group
# i = idiom, id = idiom definition, ix = idiom example
ig = element ig {
    element i { text },
    element id { text }*,
    element ix { text }*
}


# comments
cg = element cg {
    element c {text}+
}
