theme: jekyll-theme-giellalt
title: Dictionary for sme
description: An electronic monolingual dictionary in North Sámi

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
